### ISSUE TITLE
安装成功后，点击左侧任意菜单都是直接跳转到admin路由

### ISSUE THREAD

**Issue by Chenjiajing** [wenxuanjun/laravel-adminlte3#5] opened 2019-06-27 11:29 UTC
环境
laravel  5.8.17 
laravel-admin  1.7
PHP           7.2.1
laravel-adminlte3  1.2

laravel-adminlte3 安装成功后，点击左侧任意菜单都是直接跳转到/admin路由(首页),麻烦作者看下是什么原因，谢谢
 @wenxuanjun

**Comment by wenxuanjun** [comment] 2019-06-30 01:50
Thanks for your issue.

I'm not sure if the problem is caused by the update of the laravel-admin.You can try finding the way to solve it by yourself or use laravel-admin v1.6.12.😅

Sorry to tell you that it won't be fixed until the week after next because of the final exam!😂

**Comment by Chenjiajing** [comment] 2019-07-01 06:44
get it !

**Comment by wenxuanjun** [comment] 2019-07-16 07:33
Works well now.

**Closed** 2019-07-16 07:33 UTC
